export const projectWriteups = [
  {
    name: "Kanban Task Management",
    description: "A task management app with a light/dark mode toggle.",
    url: "kanban-task-management",
    requirements: [
      "View the optimal layout for the app depending on their device's screen size",
      "See hover states for all interactive elements on the page",
      "Create, read, update, and delete boards and tasks",
      "Receive form validations when trying to create/edit boards and tasks",
      "Mark subtasks as complete and move tasks between columns",
      "Hide/show the board sidebar",
      "Toggle the theme between light/dark modes",
    ],
    liveSite: "https://kanban-task-management-tan.vercel.app/",
    github: "https://github.com/davidthus/kanban-task-management",
    tools: [
      "redux",
      "react",
      "typescript",
      "styled-components",
      "figma",
      "react-hook-form",
    ],
  },
  {
    name: "Audiophile e-commerce",
    description: "A large, fully-functional e-commerce with cart and checkout.",
    url: "audiophile-ecommerce",
    requirements: [
      "View the optimal layout for the app depending on their device's screen size",
      "See hover states for all interactive elements on the page",
      "Add/Remove products from the cart",
      "Edit product quantities in the cart",
      "Fill in all fields in the checkout",
      "Receive form validations if fields are missed or incorrect during checkout",
      "See correct checkout totals depending on the products in the cart",
      "Shipping always adds $50 to the order",
      "VAT is calculated as 20% of the product total, excluding shipping",
      "See an order confirmation modal after checking out with an order summary",
    ],
    liveSite: "https://audiophile-ecommerce-one.vercel.app/",
    github: "https://github.com/davidthus/audiophile-ecommerce",
    tools: [
      "redux",
      "react",
      "typescript",
      "styled-components",
      "figma",
      "react-hook-form",
    ],
  },
  {
    name: "Product Feedback",
    description: "A CRUD product feedback app.",
    url: "product-feedback",
    requirements: [
      "View the optimal layout for the app depending on their device's screen size",
      "See hover states for all interactive elements on the page",
      "Create, read, update, and delete product feedback requests",
      "Receive form validations when trying to create/edit feedback requests",
      "Sort suggestions by most/least upvotes and most/least comments",
      "Filter suggestions by category",
      "Add comments and replies to a product feedback request",
      "Upvote product feedback requests",
    ],
    liveSite: "https://feedback-products.vercel.app/",
    github: "https://github.com/davidthus/feedback-products",
    tools: [
      "redux",
      "react",
      "typescript",
      "styled-components",
      "react-hook-form",
    ],
  },
  {
    name: "Todo App",
    description:
      "A cool todo app with theme toggle and ability to filter tasks.",
    url: "todo-app",
    requirements: [
      "View the optimal layout for the app depending on their device's screen size",
      "See hover states for all interactive elements on the page",
      "Add new todos to the list",
      "Mark todos as complete",
      "Delete todos from the list",
      "Filter by all/active/complete todos",
      "Clear all completed todos",
      "Toggle light and dark mode",
    ],
    liveSite: "https://todo-application-chi.vercel.app/",
    github: "https://github.com/davidthus/todo-application",
    tools: ["react", "styled-components"],
  },
  {
    name: "Rest Countries",
    description:
      "An API app which fetches data about all the countries in the world with optional filters.",
    url: "rest-countries",
    requirements: [
      "See all countries from the API on the homepage",
      "Search for a country using an input field",
      "Filter countries by region",
      "Click on a country to see more detailed information on a separate page",
      " Click through to the border countries on the detail page",
      "Toggle the color scheme between light and dark mode",
    ],
    liveSite: "https://rest-countries-davidthus.vercel.app/",
    github: "https://github.com/davidthus/rest-countries",
    tools: ["nextjs", "styled-components"],
  },
  {
    name: "Interactive Comments",
    description: "A CRUD, interactive comments section.",
    url: "interactive-comments",
    requirements: [
      "View the optimal layout for the app depending on their device's screen size",
      "See hover states for all interactive elements on the page",
      "Create, Read, Update, and Delete comments and replies",
      "Upvote and downvote comments",
    ],
    liveSite: "https://interactive-comments-wheat.vercel.app/",
    github: "https://github.com/davidthus/interactive-comments",
    tools: ["react", "styled-components"],
  },
  {
    name: "Sunnyside landing page",
    description: "A simplistic, bright landing page.",
    url: "sunnyside-landing-page",
    requirements: [
      "View the optimal layout for the site depending on their device's screen size",
      "See hover states for all interactive elements on the page",
    ],
    liveSite: "https://davidthus.github.io/sunnyside-landing-page/",
    github: "https://github.com/davidthus/sunnyside-landing-page",
    tools: ["scss", "javascript"],
  },
  {
    name: "Blogr landing page",
    description: "A clean landing page.",
    url: "blogr-landing-page",
    requirements: [
      "View the optimal layout for the site depending on their device's screen size",
      "See hover states for all interactive elements on the page",
    ],
    liveSite: "https://blogr-landing-page-xc56.vercel.app/",
    github: "https://github.com/davidthus/blogr-landing-page",
    tools: ["react", "styled-components"],
  },
];
