export const projectWriteups = [
  {
    name: "Kanban Task Management",
    description: "A task management app with a light/dark mode toggle.",
    url: "kanban-task-management",
    liveSite: "https://kanban-task-management-tan.vercel.app/",
    github: "https://github.com/davidthus/kanban-task-management",
    tools: [
      "redux",
      "react",
      "typescript",
      "styled-components",
      "figma",
      "react-hook-form",
    ],
  },
  {
    name: "Audiophile e-commerce",
    description: "A large, fully-functional e-commerce with cart and checkout.",
    url: "audiophile-ecommerce",
    liveSite: "https://audiophile-ecommerce-one.vercel.app/",
    github: "https://github.com/davidthus/audiophile-ecommerce",
    tools: [
      "redux",
      "react",
      "typescript",
      "styled-components",
      "figma",
      "react-hook-form",
    ],
  },
  {
    name: "Product Feedback",
    description: "A CRUD product feedback app.",
    url: "product-feedback",
    liveSite: "https://feedback-products.vercel.app/",
    github: "https://github.com/davidthus/feedback-products",
    tools: [
      "redux",
      "react",
      "typescript",
      "styled-components",
      "react-hook-form",
    ],
  },
  {
    name: "Todo App",
    description:
      "A cool todo app with theme toggle and ability to filter tasks.",
    url: "todo-app",
    liveSite: "https://todo-application-chi.vercel.app/",
    github: "https://github.com/davidthus/todo-application",
    tools: ["react", "styled-components"],
  },
  {
    name: "Rest Countries",
    description:
      "An API app which fetches data about all the countries in the world with optional filters.",
    url: "rest-countries",
    liveSite: "https://rest-countries-davidthus.vercel.app/",
    github: "https://github.com/davidthus/rest-countries",
    tools: ["nextjs", "styled-components"],
  },
  {
    name: "Interactive Comments",
    description: "A CRUD, interactive comments section.",
    url: "interactive-comments",
    liveSite: "https://interactive-comments-wheat.vercel.app/",
    github: "https://github.com/davidthus/interactive-comments",
    tools: ["react", "styled-components"],
  },
  {
    name: "Sunnyside landing page",
    description: "A simplistic, bright landing page.",
    url: "sunnyside-landing-page",
    liveSite: "https://davidthus.github.io/sunnyside-landing-page/",
    github: "https://github.com/davidthus/sunnyside-landing-page",
    tools: ["scss", "javascript"],
  },
  {
    name: "Blogr landing page",
    description: "A clean landing page.",
    url: "blogr-landing-page",
    liveSite: "https://blogr-landing-page-xc56.vercel.app/",
    github: "https://github.com/davidthus/blogr-landing-page",
    tools: ["react", "styled-components"],
  },
];
